name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: adixlucifer0011
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?palette=github-dark

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add dist/

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update contribution snake"
            git push
          fi
